services:
  # bff
  bff:
    build: ./docker/bff/
    container_name: hackz-ankylo-bff
    volumes:
      - ./bff:/app
    ports:
      - "3000:3000"

  # microservices
  auth:
    build: 
      context: ./microservice/auth
      dockerfile: ./src/main/docker/Dockerfile.jvm
    container_name: hackz-ankylo-auth
    platform: linux/x86_64
    tty: true
    env_file:
      - ./secrets/.env
    ports:
      - "5001:8080"
  qr:
    build: 
      context: ./microservice/qr
      dockerfile: ./src/main/docker/Dockerfile.jvm
    container_name: hackz-ankylo-qr
    platform: linux/x86_64
    tty: true
    env_file:
      - ./secrets/.env
    ports:
      - "5002:8080"

  # monitor
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: hackz-ankyolo-uptime-kuma
    volumes:
      - ./docker/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3001:3001"

  # tunnel
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: hackz-ankylo-tunnel
    restart: always
    command: tunnel run
    env_file:
      - ./secrets/.env