services:
  # bff
  bff:
    build: ./docker/bff/
    container_name: hackz-ankylo-bff
    volumes:
      - ./bff:/app
    ports:
      - "3000:3000"
    depends_on:
      auth:
        condition: service_healthy
      qr:
        condition: service_healthy
      animate-qr:
        condition: service_healthy

  # microservices
  auth:
    build: 
      context: ./microservice/auth
      dockerfile: ./src/main/docker/Dockerfile.jvm
    container_name: hackz-ankylo-auth
    platform: linux/x86_64
    tty: true
    env_file:
      - ./secrets/.env
    ports:
      - "5001:8080"
    healthcheck:
      test: "curl -f http://localhost:8080/healthcheck || exit 1"
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s
  qr:
    build: 
      context: ./microservice/qr
      dockerfile: ./src/main/docker/Dockerfile.jvm
    container_name: hackz-ankylo-qr
    platform: linux/x86_64
    tty: true
    env_file:
      - ./secrets/.env
    ports:
      - "5002:8080"
    healthcheck:
      test: "curl -f http://localhost:8080/healthcheck || exit 1"
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s
  animate-qr:
    build:
      context: ./microservice/animate-qr
      dockerfile: ../../docker/animate-qr/Dockerfile
    container_name: hackz-ankylo-animate-qr
    platform: linux/x86_64
    env_file:
      - ./secrets/.env
    ports:
      - "5003:8080"
    healthcheck:
      test: "curl -f http://localhost:8080/healthcheck || exit 1"
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s

  # monitor
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: hackz-ankyolo-uptime-kuma
    volumes:
      - ./docker/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3001:3001"
    depends_on:
      tunnel:
        condition: service_started

  # tunnel
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: hackz-ankylo-tunnel
    restart: always
    command: tunnel run
    env_file:
      - ./secrets/.env
    depends_on:
      bff:
        condition: service_started