name: Update Submodule

on:
  repository_dispatch:
    types: [update_submodule]

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Git config
        run: |
          git config --global user.name 'naoido'
          git config --global user.email 'naoto.kido072@gmail.com'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: feature/update-submodule
          submodules: true
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Commit
        id: commit
        run: |
          git submodule update --remote
          git add .
          cd env && SUBMODULE_COMMIT=$(git rev-parse --short=7 HEAD) && cd -
          git commit -m "Update submodule [$SUBMODULE_COMMIT]"
          git push
          echo "commit_id=$SUBMODULE_COMMIT" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        run: gh pr create -B develop -H feature/update-submodule --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
